# Generated by Django 6.0.8 on 2026-09-08 13:33

import branches.models
import django.db.models.deletion
import modelcluster.fields
from collections import defaultdict
from django.db import migrations, models


def transfer_data(apps, schema_editor):
    Role = apps.get_model('branches', 'Role')
    MemberRoleAssignment = apps.get_model('branches', 'MemberRoleAssignment')
    BranchRoleConfig = apps.get_model('branches', 'BranchRoleConfig')
    BranchMemberPlacement = apps.get_model('branches', 'BranchMemberPlacement')
    BranchPage = apps.get_model('branches', 'BranchPage')
    MemberListingPage = apps.get_model('branches', 'MemberListingPage')

    listing_pages = {}
    branch_path_map = {
        branch_page.path: branch_page.branch_type 
        for branch_page in BranchPage.objects.all()
    }
    for listing_page in MemberListingPage.objects.all():
        branch_path = listing_page.path[:-4]
        if branch_path in branch_path_map:
            listing_pages[branch_path_map[branch_path]] = listing_page

    for placement in BranchMemberPlacement.objects.all():
        for role_assignment in placement.role_assignments.all():
            role = role_assignment.role
            MemberRoleAssignment.objects.create(
                member = placement.member,
                role = role,
            )
            if listing_pages[role.branch]:
                BranchRoleConfig.objects.create(
                    page=listing_pages[role.branch],
                    role=role_assignment.role,
                    hierarchy_tier=next((i for i, entry in enumerate(Role._meta.get_field('tier').choices) if entry[0] == role.tier), None),
                    role_display=role.name,
                )

    for branch, page in listing_pages.items():
        page.save()
    
    for role in Role.objects.all():
        if role.constituency_fsl != "none":
            role.constituency = role.constituency_fsl
        else:
            role.constituency = role.constituency_class
        role.name = f"[! {role.branch}] {role.name}"
        role.save()


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0012_branchpage_image_credit_branchpage_image_credit_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='constituency',
            field=models.CharField(choices=branches.models.constituency_choices, default='none', help_text='Graduating class or FSL association this role represents, if any.', max_length=20),
        ),
        migrations.AddField(
            model_name='role',
            name='positions',
            field=models.PositiveIntegerField(blank=True, help_text='Number of positions.', null=True),
        ),
        migrations.CreateModel(
            name='BranchRoleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('role_display', models.CharField(blank=True, help_text='Role name override, e.g. Senate Secretary -> Secretary', max_length=255)),
                ('hierarchy_tier', models.IntegerField(choices=[(0, 'Presiding Officer'), (1, 'Officers'), (2, 'Committee Chairs'), (3, 'Voting Members'), (4, 'Non-voting Members')], default=3, help_text='Display tier on page.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_configs', to='branches.memberlistingpage')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='branches.role')),
            ],
            options={
                'ordering': ['hierarchy_tier', 'role'],
                'verbose_name': 'Role Config',
            },
        ),
        migrations.CreateModel(
            name='ClassCouncilRoleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('role_display', models.CharField(blank=True, help_text='Role name override, e.g. Senate Secretary -> Secretary', max_length=255)),
                ('hierarchy_tier', models.IntegerField(choices=[(0, 'President'), (1, 'Officers'), (2, 'Committee Chairs'), (3, 'Voting Members')], default=3, help_text='Display tier on page.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_configs', to='branches.classcouncilpage')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='branches.role')),
            ],
            options={
                'ordering': ['hierarchy_tier', 'role'],
                'verbose_name': 'Role Config',
            },
        ),
        migrations.CreateModel(
            name='CommitteeRoleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('role_display', models.CharField(blank=True, help_text='Role name override, e.g. Senate Secretary -> Secretary', max_length=255)),
                ('hierarchy_tier', models.IntegerField(choices=[(0, 'Chairperson')], default=0, help_text='Display tier on page.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_configs', to='branches.committeepage')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='branches.role')),
            ],
            options={
                'ordering': ['hierarchy_tier', 'role'],
                'verbose_name': 'Role Config',
            },
        ),
        migrations.CreateModel(
            name='MemberRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='branches.memberprofile')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='branches.role')),
            ],
            options={
                'verbose_name': 'Member-Role Assignment',
                'verbose_name_plural': 'Member-Role Assignments',
                'ordering': ['member', 'role'],
            },
        ),
        migrations.RunPython(
            transfer_data,
        ),
        migrations.RemoveField(
            model_name='branchmemberrole',
            name='placement',
        ),
        migrations.RemoveField(
            model_name='branchmemberrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='classcouncilmemberplacement',
            name='member',
        ),
        migrations.RemoveField(
            model_name='classcouncilmemberplacement',
            name='page',
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='class_year',
            field=models.CharField(choices=branches.models.member_class_choices, default='', help_text='Class year, e.g. 2027 or Graduate', max_length=20, blank=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email (RCS ID)'),
        ),
        migrations.RemoveField(
            model_name='role',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='role',
            name='constituency_class',
        ),
        migrations.RemoveField(
            model_name='role',
            name='constituency_fsl',
        ),
        migrations.RemoveField(
            model_name='role',
            name='tier',
        ),
        migrations.AlterField(
            model_name='committeememberplacement',
            name='committee_role',
            field=models.CharField(default='Member', max_length=50),
        ),
        migrations.AlterField(
            model_name='committeememberplacement',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_placements', to='branches.committeepage'),
        ),
        migrations.DeleteModel(
            name='BranchMemberPlacement',
        ),
        migrations.DeleteModel(
            name='BranchMemberRole',
        ),
        migrations.DeleteModel(
            name='ClassCouncilMemberPlacement',
        ),
    ]
